name: Build and Test Flask App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run Docker container and execute tests
        run: docker run --name flask-container flask-app pytest -v tests/

      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop flask-container
          docker rm flask-container